algoritmo "semnome"
var
   media: REAL
   N, cont, soma, num: INTEIRO
inicio
      Escreva("Quantas vezes gostaria de digitar números para a somatória?: ")
      Leia(N)
      Para cont <- 1 ate n faca
           Escreva("Digite um número: ")
           Leia(num)
           soma <- soma + num
      FimPara
      
      media <- soma/N
      
      Escreval("A soma dos números é: ", soma)
      Escreval("A média dos números é: ", media)
fimalgoritmo
