algoritmo "semnome"
//86) Crie um programa que tenha um procedimento Gerador() que, quando chamado,
//mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
//Ex: Ao chamar Gerador() aparece:
//+-------=======------+
// Olá, Mundo!
//+-------=======------+
var

Procedimento gerador()
Inicio
      Escreval("+-------=======------+")
FimProcedimento
inicio
      gerador()
      Escreval("      Olá, Mundo!      ")
      gerador()
fimalgoritmo
