algoritmo "semnome"
//48) Faça um programa que leia 7 números inteiros e no final mostre o somatório entre eles.
var
   cont, num, soma: INTEIRO
inicio
      Enquanto (cont < 7) faca
               Escreva("Digite um número: ")
               Leia(num)
               soma <- soma + num
               cont <- cont + 1
      FimEnquanto
      Escreval("A soma dos 7 número é de ", soma)
fimalgoritmo
