algoritmo "Exercício07"
var
   distancia: REAL
inicio
      Escreva("Digite uma distância em metros: ")
      Leia(distancia)
      Escreval("A distância de, ", distancia, " corresponde a: ")
      Escreval(distancia/1000, "Km")
      Escreval(distancia/100, "Hm")
      Escreval(distancia/10, "Dam")
      Escreval(distancia*10, "dm")
      Escreval(distancia*100, "cm")
      Escreval(distancia*1000, "mm")
fimalgoritmo
